### ISSUE TITLE
Stuck on 'Queue file' while training

### ISSUE THREAD

**Issue by jimz7** [cmb-chula/pylon#1]
Hello, really appreciate the code release and the amazing results!
I followed the instruction and trying to run `python train_nih_run.py`, and for the first few times, I get some training results successfully and my `/log` directory got updated. But after that when I runing the training command, I always stuck on the 'Queue file' step, and it seems that the training process never started and the `/log` directory never got updated.
How can I solve this problems? Really appreciate the help!
![image](https://user-images.githubusercontent.com/37298719/177045865-2e3dd5ea-2f1f-44ea-a8f0-07a2b8931a5e.png)

**Comment by konpatp** [comment]
`mlkit.queue.<n>` files were created as a part of parallelization. Each process will acquire one "lock file". If it can lock on a file, it will proceed. If it cannot, it will wait for the lock file to be acquired. Usually, the lock file will be released after the owner process ends. However, if the owner process didn't stop properly, it will fail to release the lock file, never releasing it. 

To solve this, you can remove `mlkit.queue.<n>` files from `~` manually.

**Comment by jimz7** [comment]
Thanks!
