### ISSUE TITLE
Confused about the training

### ISSUE THREAD

**Issue by jimz7** [cmb-chula/pylon#2]
Hello,
I'm currently running `python train_nih_run.py`, and I have several questions:

1. How long does the training normally take? I'm training on an RTX A6000 and have ran for around 20 hours and haven't finished yet.
2. It seems that the `python train_nih_run.py` command will train all the models one by one. How can I only train the pylon model?
3. When I check the files in `/log`, I can see that some experiment ended even when 'train' hasn't reached 100%. Is this true?

Thank you for your help!

**Comment by konpatp** [comment]
Answers:

1. It usually took less than a day. I believe it should be < 10 hours. It usually runs with > 5 iters/sec. If you see less than this, the bottleneck may be the I/O (slow hard drive).
2. You just need to look at `train_nih_run.py`. The code is only 38 lines long. It should be intuitive for you to comment some certain lines. 
3. There is an early stopping mechanism based on the validation score. If the validation score does not improve for 2 consecutive epochs, it early stops.
